import os
import random
from item_class import Item
from character_class import Character,Fighter,Mage,Barbarian,Enemy

#items generated by chatgpt    
# Create all items
items = [
    
    # empty
    Item("No Weapon", "Weapon"),
    Item("No Helmet", "Helmet"),
    Item("No Armor", "Armor"),
    Item("No Shoes", "Shoes"),

    # Weapons
    Item("Iron Longsword", "Weapon", strength=10),
    Item("Staff of Emberlight", "Weapon", mana=40, dodge=5),
    Item("Dwarven Battleaxe", "Weapon", health=20, strength=20),
    Item("Silent Dagger", "Weapon", strength=8, dodge=12),
    Item("Gnome Spark Blaster", "Weapon", mana=30, dodge=10),
    Item("Elven Bow of Whispers", "Weapon", strength=15, dodge=15),
    Item("Barbarian’s War Maul", "Weapon", strength=25, dodge=-10),

    # Helmets
    Item("Helm of Vitality", "Helmet", health=30),
    Item("Mage’s Circlet", "Helmet", mana=50),
    Item("Iron Skullcap", "Helmet", health=15, strength=5),
    Item("Cap of Evasion", "Helmet", dodge=10),
    Item("Runed Battle Helm", "Helmet", health=10, strength=20),
    Item("Dome of Focus", "Helmet", mana=20, dodge=5),
    Item("Shadow Hood", "Helmet", mana=20, dodge=15),

    # Armor
    Item("Chainmail Vest", "Armor", health=25),
    Item("Robe of the Arcanist", "Armor", mana=60),
    Item("Dwarven Plate", "Armor", health=50, strength=10),
    Item("Leather Jerkin", "Armor", dodge=15),
    Item("Battlelord’s Chestguard", "Armor", health=30, strength=30),
    Item("Gnome-Tinker’s Overcoat", "Armor", mana=40, dodge=10),
    Item("Elven Wind Tunic", "Armor", mana=20, dodge=20),

    # Shoes
    Item("Boots of Speed", "Shoes", dodge=20),
    Item("Steel-Toed Boots", "Shoes", health=15),
    Item("Mystic Sandals", "Shoes", mana=30, dodge=10),
    Item("Daggerstep Boots", "Shoes", strength=10, dodge=15),
    Item("Barbaric Stompers", "Shoes", strength=25, dodge=-10),
    Item("Treads of the Quick", "Shoes", health=10, dodge=20),
    Item("Runed Greaves", "Shoes", health=20, mana=20),

    # Legendary Artifacts
    Item("Soulrender Blade", "Weapon", health=50, strength=50, mana=30),
    Item("Crown of the Forgotten King", "Helmet", health=40, mana=100, dodge=25)
]

# Test — print all items
# for item in items:
#     print(item)
player = Fighter('joey','human', 150,10,30,10)
goblin = Character('bingo', 'goblin','gooby', 150,10,30,10)
player.equip(Item("Iron Longsword", "Weapon", strength=10))
player.equip(Item("Boots of Speed", "Shoes", dodge=20))
goblin.equip(Item("Chainmail Vest", "Armor", health=25))
print(player.return_stats())
print(goblin.return_stats())
print()
while(player.health>0 and goblin.health>0):
    player.attack(goblin)
    goblin.attack(player)

  
    

    

    


def main():
    os.system('cls||clear')
    print('''

·▄▄▄▄   ▄▄▄· ▄▄▄  ▄ •▄     ·▄▄▄▄  ▄• ▄▌ ▐ ▄  ▄▄ • ▄▄▄ .       ▐ ▄ 
██▪ ██ ▐█ ▀█ ▀▄ █·█▌▄▌▪    ██▪ ██ █▪██▌•█▌▐█▐█ ▀ ▪▀▄.▀·▪     •█▌▐█
▐█· ▐█▌▄█▀▀█ ▐▀▀▄ ▐▀▀▄·    ▐█· ▐█▌█▌▐█▌▐█▐▐▌▄█ ▀█▄▐▀▀▪▄ ▄█▀▄ ▐█▐▐▌
██. ██ ▐█ ▪▐▌▐█•█▌▐█.█▌    ██. ██ ▐█▄█▌██▐█▌▐█▄▪▐█▐█▄▄▌▐█▌.▐▌██▐█▌
▀▀▀▀▀•  ▀  ▀ .▀  ▀·▀  ▀    ▀▀▀▀▀•  ▀▀▀ ▀▀ █▪·▀▀▀▀  ▀▀▀  ▀█▄▀▪▀▀ █▪

          ''')
    name=input("What is your character's name? ")
    
    print('''
Choose a race:
1) Human (120hp, 12 strength, 120 mana, 18% dodge)
2) Elf (100hp, 8 strength, 160 mana, 24% dodge)
3) Dwarf (160hp, 14 strength, 80 mana, 12% dodge)
4) Gnome (80hp, 6 strength, 140 mana, 30% dodge)
          ''')
    race=''
    while(race!='1' and race!='2' and race!='3' and race!='4'):
        race=input("Race? (option 1,2,3,4): ")
    
    print('''
Choose a class:
1) Fighter (20% chance to double strike, +40hp, +4 strength, +3 dodge)
2) Mage (1.5x spell damage, +60 mana, +3 dodge)
3) Barbarian (regenerates health after attacking, +80hp, +6 strength, -20 mana)
          ''')
    classa=''
    while(classa!='1' and classa!='2' and classa!='3'):
        classa=input("Class? (option 1,2,3): ")
    
    hero='' 
    if classa=='1':
        if race=='1':
            hero=Fighter(name,'Human',120,12,120,18)
        if race=='2':
            hero=Fighter(name,'Elf',100,8,160,24)
        if race=='3':
            hero=Fighter(name,'Dwarf',160,14,80,12)
        if race=='4':
            hero=Fighter(name,'Gnome',80,6,140,30)

    if classa=='2':
        if race=='1':
            hero=Mage(name,'Human',120,12,120,18)
        if race=='2':
            hero=Mage(name,'Elf',100,8,160,24)
        if race=='3':
            hero=Mage(name,'Dwarf',160,14,80,12)
        if race=='4':
            hero=Mage(name,'Gnome',80,6,140,30)

    if classa=='3':
        if race=='1':
            hero=Barbarian(name,'Human',120,12,120,18)
        if race=='2':
            hero=Barbarian(name,'Elf',100,8,160,24)
        if race=='3':
            hero=Barbarian(name,'Dwarf',160,14,80,12)
        if race=='4':
            hero=Barbarian(name,'Gnome',80,6,140,30)
            
    print(hero.return_stats()['name'])
    print(hero.name)

    
# main()