import os
import random
from item_class import Item
from character_class import Character,Fighter,Mage,Barbarian,Enemy

#items generated by chatgpt    
# Create all items
items = [
    
    # empty
    Item("No Weapon", "Weapon"),
    Item("No Helmet", "Helmet"),
    Item("No Armor", "Armor"),
    Item("No Shoes", "Shoes"),

    # Weapons
    Item("Iron Longsword", "Weapon", strength=10),
    Item("Staff of Emberlight", "Weapon", mana=40, dodge=5),
    Item("Dwarven Battleaxe", "Weapon", health=20, strength=20),
    Item("Silent Dagger", "Weapon", strength=8, dodge=12),
    Item("Gnome Spark Blaster", "Weapon", mana=30, dodge=10),
    Item("Elven Bow of Whispers", "Weapon", strength=15, dodge=15),
    Item("Barbarian’s War Maul", "Weapon", strength=25, dodge=-10),

    # Helmets
    Item("Helm of Vitality", "Helmet", health=30),
    Item("Mage’s Circlet", "Helmet", mana=50),
    Item("Iron Skullcap", "Helmet", health=15, strength=5),
    Item("Cap of Evasion", "Helmet", dodge=10),
    Item("Runed Battle Helm", "Helmet", health=10, strength=20),
    Item("Dome of Focus", "Helmet", mana=20, dodge=5),
    Item("Shadow Hood", "Helmet", mana=20, dodge=15),

    # Armor
    Item("Chainmail Vest", "Armor", health=25),
    Item("Robe of the Arcanist", "Armor", mana=60),
    Item("Dwarven Plate", "Armor", health=50, strength=10),
    Item("Leather Jerkin", "Armor", dodge=15),
    Item("Battlelord’s Chestguard", "Armor", health=30, strength=30),
    Item("Gnome-Tinker’s Overcoat", "Armor", mana=40, dodge=10),
    Item("Elven Wind Tunic", "Armor", mana=20, dodge=20),

    # Shoes
    Item("Boots of Speed", "Shoes", dodge=20),
    Item("Steel-Toed Boots", "Shoes", health=15),
    Item("Mystic Sandals", "Shoes", mana=30, dodge=10),
    Item("Daggerstep Boots", "Shoes", strength=10, dodge=15),
    Item("Barbaric Stompers", "Shoes", strength=25, dodge=-10),
    Item("Treads of the Quick", "Shoes", health=10, dodge=20),
    Item("Runed Greaves", "Shoes", health=20, mana=20),

    # Legendary Artifacts
    Item("Soulrender Blade", "Weapon", health=50, strength=50, mana=30),
    Item("Crown of the Forgotten King", "Helmet", health=40, mana=100, dodge=25)
]

# Test — print all items
# for item in items:
#     print(item)
# player = Fighter('joey','Human',120,12,120,18)
# goblin = Character('bingo', 'goblin','gooby', 150,10,30,10)
# player.equip(Item("Iron Longsword", "Weapon", strength=10))
# player.equip(Item("Boots of Speed", "Shoes", dodge=20))
# goblin.equip(Item("Chainmail Vest", "Armor", health=25))
# print(player.return_stats())
# print(goblin.return_stats())
# print()
# while(player.health>0 and goblin.health>0):
#     player.spell(goblin)
#     goblin.attack(player)


shop_items=[]
for i in range(5):
    shop_items.append(random.randint(4,31))



def main():
    os.system('cls||clear')
    print(f"num of items: {len(items)}")
    print(f"shop items: {shop_items}")
    print('''
·▄▄▄▄   ▄▄▄· ▄▄▄  ▄ •▄     ·▄▄▄▄  ▄• ▄▌ ▐ ▄  ▄▄ • ▄▄▄ .       ▐ ▄ 
██▪ ██ ▐█ ▀█ ▀▄ █·█▌▄▌▪    ██▪ ██ █▪██▌•█▌▐█▐█ ▀ ▪▀▄.▀·▪     •█▌▐█
▐█· ▐█▌▄█▀▀█ ▐▀▀▄ ▐▀▀▄·    ▐█· ▐█▌█▌▐█▌▐█▐▐▌▄█ ▀█▄▐▀▀▪▄ ▄█▀▄ ▐█▐▐▌
██. ██ ▐█ ▪▐▌▐█•█▌▐█.█▌    ██. ██ ▐█▄█▌██▐█▌▐█▄▪▐█▐█▄▄▌▐█▌.▐▌██▐█▌
▀▀▀▀▀•  ▀  ▀ .▀  ▀·▀  ▀    ▀▀▀▀▀•  ▀▀▀ ▀▀ █▪·▀▀▀▀  ▀▀▀  ▀█▄▀▪▀▀ █▪

    ''')
    name=input("What is your character's name? ")
    
    print('''
Choose a race:
1) Human (120hp, 12 strength, 120 mana, 18% dodge)
2) Elf (100hp, 8 strength, 160 mana, 24% dodge)
3) Dwarf (160hp, 14 strength, 80 mana, 12% dodge)
4) Gnome (80hp, 6 strength, 140 mana, 30% dodge)
          ''')
    race=''
    while(race!='1' and race!='2' and race!='3' and race!='4'):
        race=input("Race? (option 1,2,3,4): ")
    
    print('''
Choose a class:
1) Fighter (20% chance to double strike, +40hp, +4 strength, +3 dodge)
2) Mage (1.5x spell damage, +60 mana, +3 dodge)
3) Barbarian (regenerates health after attacking, +80hp, +6 strength, -20 mana)
          ''')
    classa=''
    while(classa!='1' and classa!='2' and classa!='3'):
        classa=input("Class? (option 1,2,3): ")
    
    hero='' 
    if classa=='1':
        if race=='1':
            hero=Fighter(name,'Human',120,12,120,18)
        if race=='2':
            hero=Fighter(name,'Elf',100,8,160,24)
        if race=='3':
            hero=Fighter(name,'Dwarf',160,14,80,12)
        if race=='4':
            hero=Fighter(name,'Gnome',80,6,140,30)

    if classa=='2':
        if race=='1':
            hero=Mage(name,'Human',120,12,120,18)
        if race=='2':
            hero=Mage(name,'Elf',100,8,160,24)
        if race=='3':
            hero=Mage(name,'Dwarf',160,14,80,12)
        if race=='4':
            hero=Mage(name,'Gnome',80,6,140,30)

    if classa=='3':
        if race=='1':
            hero=Barbarian(name,'Human',120,12,120,18)
        if race=='2':
            hero=Barbarian(name,'Elf',100,8,160,24)
        if race=='3':
            hero=Barbarian(name,'Dwarf',160,14,80,12)
        if race=='4':
            hero=Barbarian(name,'Gnome',80,6,140,30)
    os.system('cls||clear')      
    print(hero.return_stats())
    print('''
▄▄▄ . ▐ ▄ ▄▄▄▄▄▄▄▄ .▄▄▄  ▪   ▐ ▄  ▄▄ •     ·▄▄▄▄  ▄• ▄▌ ▐ ▄  ▄▄ • ▄▄▄ .       ▐ ▄ 
▀▄.▀·•█▌▐█•██  ▀▄.▀·▀▄ █·██ •█▌▐█▐█ ▀ ▪    ██▪ ██ █▪██▌•█▌▐█▐█ ▀ ▪▀▄.▀·▪     •█▌▐█
▐▀▀▪▄▐█▐▐▌ ▐█.▪▐▀▀▪▄▐▀▀▄ ▐█·▐█▐▐▌▄█ ▀█▄    ▐█· ▐█▌█▌▐█▌▐█▐▐▌▄█ ▀█▄▐▀▀▪▄ ▄█▀▄ ▐█▐▐▌
▐█▄▄▌██▐█▌ ▐█▌·▐█▄▄▌▐█•█▌▐█▌██▐█▌▐█▄▪▐█    ██. ██ ▐█▄█▌██▐█▌▐█▄▪▐█▐█▄▄▌▐█▌.▐▌██▐█▌
 ▀▀▀ ▀▀ █▪ ▀▀▀  ▀▀▀ .▀  ▀▀▀▀▀▀ █▪·▀▀▀▀     ▀▀▀▀▀•  ▀▀▀ ▀▀ █▪·▀▀▀▀  ▀▀▀  ▀█▄▀▪▀▀ █▪
    ''')
    a = input("Press ENTER to start")
    
    #--------------- MAIN GAME LOOP --------------------------
    game_loop=True
    while(game_loop):
        os.system('cls||clear')
        print('''
 ▄▄·       • ▌ ▄ ·. • ▌ ▄ ·.  ▄▄▄·  ▐ ▄ ·▄▄▄▄  
▐█ ▌▪▪     ·██ ▐███▪·██ ▐███▪▐█ ▀█ •█▌▐███▪ ██ 
██ ▄▄ ▄█▀▄ ▐█ ▌▐▌▐█·▐█ ▌▐▌▐█·▄█▀▀█ ▐█▐▐▌▐█· ▐█▌
▐███▌▐█▌.▐▌██ ██▌▐█▌██ ██▌▐█▌▐█ ▪▐▌██▐█▌██. ██ 
·▀▀▀  ▀█▄▀▪▀▀  █▪▀▀▀▀▀  █▪▀▀▀ ▀  ▀ ▀▀ █▪▀▀▀▀▀• 

1) Enter New Room (d10) (10% empty room, 20% treasure room, 70% monster room)
2) Enter Shop
3) Summon Dark Wizard!
        ''')
        command=''
        while(command!='1' and command!='2' and command!='3'):
            command=input("(option 1,2,3): ")
        
        #----------------- enter new room-------------------------
        if command=='1':
            os.system('cls||clear')
            die=random.randint(1,10)
            print(f"die roll = {die}")
            if die==1:
                print('''
▄▄▄ .• ▌ ▄ ·.  ▄▄▄·▄▄▄▄▄ ▄· ▄▌    ▄▄▄              • ▌ ▄ ·. 
▀▄.▀··██ ▐███▪▐█ ▄█•██  ▐█▪██▌    ▀▄ █·▪     ▪     ·██ ▐███▪
▐▀▀▪▄▐█ ▌▐▌▐█· ██▀· ▐█.▪▐█▌▐█▪    ▐▀▀▄  ▄█▀▄  ▄█▀▄ ▐█ ▌▐▌▐█·
▐█▄▄▌██ ██▌▐█▌▐█▪·• ▐█▌· ▐█▀·.    ▐█•█▌▐█▌.▐▌▐█▌.▐▌██ ██▌▐█▌
▀▀▀ ▀▀  █▪▀▀▀.▀    ▀▀▀   ▀ •     .▀  ▀ ▀█▄▀▪ ▀█▄▀▪▀▀  █▪▀▀▀
                ''')
                a = input("Press ENTER to continue")
            
            elif die<=3:
                print('''
▄▄▄▄▄▄▄▄  ▄▄▄ . ▄▄▄· .▄▄ · ▄• ▄▌▄▄▄  ▄▄▄ .
•██  ▀▄ █·▀▄.▀·▐█ ▀█ ▐█ ▀. █▪██▌▀▄ █·▀▄.▀·
▐█.▪▐▀▀▄ ▐▀▀▪▄▄█▀▀█ ▄▀▀▀█▄█▌▐█▌▐▀▀▄ ▐▀▀▪▄
▐█▌·▐█•█▌▐█▄▄▌▐█ ▪▐▌▐█▄▪▐█▐█▄█▌▐█•█▌▐█▄▄▌
▀▀▀ .▀  ▀ ▀▀▀  ▀  ▀  ▀▀▀▀  ▀▀▀ .▀  ▀ ▀▀▀ 
                ''')
                found_item = items[random.randint(0,33)]
                print(f"current Weapon: {hero.weapon}")
                print(f"current Helmet: {hero.helmet}")
                print(f"current Armor: {hero.armor}")
                print(f"current Shoes: {hero.shoes}")
                print(f"you found item {found_item}, do you want to equip? y/n")
                equip=''
                while(equip!='y' and equip!='n'):
                    equip=input("(option y/n): ")
                if equip=='y':
                    hero.equip(found_item)
                    print(f"you equipped {found_item.name}")
                    a = input(f"you equipped {found_item.name}")
            else:
                print('''
▄▄▄ . ▐ ▄ ▄▄▄ .• ▌ ▄ ·.  ▄· ▄▌
▀▄.▀·•█▌▐█▀▄.▀··██ ▐███▪▐█▪██▌
▐▀▀▪▄▐█▐▐▌▐▀▀▪▄▐█ ▌▐▌▐█·▐█▌▐█▪
▐█▄▄▌██▐█▌▐█▄▄▌██ ██▌▐█▌ ▐█▀·.
▀▀▀ ▀▀ █▪ ▀▀▀ ▀▀  █▪▀▀▀  ▀ • 
                ''')
                a = input("Press ENTER to continue")
                monster = Character('Monster', 'ghost', 'ghoul', random.randint(80,120),random.randint(6,14),random.randint(80,160),random.randint(0,30),)
                
                #------------- attack loop -------------------
                while(monster.health>0 and hero.health>0):
                    print(f'''
Choose :
1) Attack
2) Cast  Spell (current mana{hero.mana})
3) View Stats
                    ''')
                    at=''
                    while(at!='1' and at!='2'and at!='3'):
                        at=input("(option 1,2,3): ")
                    if at=='1':
                        pass
                    elif at=='2':
                        pass
                    elif at=='3':
                        pass
        #----------------- Shop -------------------------
        elif command=='2':
            pass
        #----------------- fight dark wizard -------------------------
        elif command=='3':
            pass
            
            
        
main()